server:
  port: 50003
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true
  data:
    mongodb:
      database: tasks
      host: localhost
       
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
management:
  security:
    enabled: false
  health:
    defaults: true
    sensitive: true
  endpoints:
    web:
      expose: "*"
    health:
      show-details: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
      
amqp:
  tasks:
    exchange:
      created:
        task: tasks_created
      updated:
        task: tasks_updated
    key:
      created:
        request: tasks_created
      updated:
        request: tasks_updated
        
  events:
    queue:
      created:
        request: event_request_queue
    exchange:
      created: events_created
      
    key:
      created:
        request: event_created 
  
  
projects:
  service: PROJECTS
  
events:
  service: EVENTS  